fp16: True
per_device_eval_batch_size: 10
dataloader_num_workers: &num_workers 8
data_seed: &data_seed 0
seed: 32

## logging

report_to: ['tensorboard']



# MODEL

model:
  freeze_llm: True
  freeze_vfm: False
  freeze_dm: True
  llm_model_path: &tokenizer_path assets/lmsys/vicuna-7b-v1.5
  # llm_model_path: &tokenizer_path assets/lmsys/vicuna-13b-v1.3
  num_img_token: &img_len 77
  cross_attention_frequency: 4

  dataset_to_ignore_noimage_cond_loss: [laion_en, laion_coco]

  visual_tokenizer_config:
    sniffer_model_path: assets/laion/CLIP-convnext_base_w_320-laion_aesthetic-s13B-b82K
    # sniffer_model_path: assets/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup
    # sniffer_model_path: assets/openai/clip-vit-large-patch14
    # sniffer_model_path: assets/openai/clip-vit-base-patch16

    perceiver_config:
      num_queries: 77
      hidden_size: 768
      encoder_hidden_size: 1024
      cross_attention_frequency: 2
      num_hidden_layers: 12
      num_attention_heads: 12
      qk_normalization: True
  image_decoder_config:
    pretrained_model_name_or_path: assets/stabilityai/stable-diffusion-2-1-base
    sd_base_seed: 0
    sd_use_random_seed: False
    perceiver_config:
      num_queries: 77
      hidden_size: 1024
      encoder_hidden_size: 4096
      # encoder_hidden_size: 5120
      cross_attention_frequency: 1
      num_hidden_layers: 1
      num_attention_heads: 16
      hidden_dropout_prob: 0.
      attention_probs_dropout_prob: 0.
data:
  val:

    - name: refcoco_val
      data_root: datasets/coco/train2014
      annt_root: datasets/refcoco

      collator: GroundingEvalCollator
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path
      collate_mode: generate_grounding
      collate_task: grounding
      # ignore_soi_token_loss: True
      # ignore_bos2soi_token_loss: True

      transform: &val_transform
        aug_type: 'dual_numpy'
        resolution: &image_size 448
        resolution2: &image_size_dec 512
        center_crop: False
        random_flip: False


    - name: refcocog_val
      data_root: datasets/coco/train2014
      annt_root: datasets/refcoco

      collator: GroundingEvalCollator
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path
      collate_mode: generate_grounding
      collate_task: grounding
      # ignore_soi_token_loss: True
      # ignore_bos2soi_token_loss: True

      transform: *val_transform


    - name: refcoco+_val
      data_root: datasets/coco/train2014
      annt_root: datasets/refcoco

      collator: GroundingEvalCollator
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path
      collate_mode: generate_grounding
      collate_task: grounding
      # ignore_soi_token_loss: True
      # ignore_bos2soi_token_loss: True

      transform: *val_transform