# Training Arguments
fp16: True
per_device_eval_batch_size: 10
dataloader_num_workers: &num_workers 8
data_seed: &data_seed 0
seed: 32

## logging

report_to: ['tensorboard']

## deepspeed

# deepspeed: './uni_interleaved/configs/deepspeed_zero1.json'


# MODEL

model:
  freeze_llm: True
  freeze_vfm: True
  freeze_dm: True
  spatial_shapes: [56,28,14]
  llm_model_path: &tokenizer_path assets/lmsys/vicuna-7b-v1.5
  # llm_model_path: &tokenizer_path assets/lmsys/vicuna-13b-v1.3
  num_img_token: &img_len 77
  cross_attention_frequency: 4

  dataset_to_ignore_noimage_cond_loss: [laion_en, laion_coco]

  visual_tokenizer_config:
    sniffer_model_path: assets/laion/CLIP-convnext_base_w_320-laion_aesthetic-s13B-b82K
    # sniffer_model_path: assets/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup
    # sniffer_model_path: assets/openai/clip-vit-large-patch14
    # sniffer_model_path: assets/openai/clip-vit-base-patch16

    perceiver_config:
      num_queries: 77
      hidden_size: 768
      encoder_hidden_size: 1024
      cross_attention_frequency: 2
      num_hidden_layers: 12
      num_attention_heads: 12
      qk_normalization: True
  image_decoder_config: null

data:
  val:
    - name: imagenet-a

      data_root: ''
      annt_file: datasets/robustvqa/robustvqa_test.json
      phase: 'a'
      collator: ImageNetEvalCollator
      collate_mode: generate_imagenet
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path

      transform: &val_transform
        aug_type: 'dual_numpy'
        resolution: &image_size 448
        resolution2: &image_size_dec 512
        center_crop: False
        random_flip: False

    - name: imagenet-r

      data_root: ''
      annt_file: datasets/robustvqa/robustvqa_test.json
      phase: 'r'
      collator: ImageNetEvalCollator
      collate_mode: generate_imagenet
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path

      transform: *val_transform
      
    - name: imagenetv2

      data_root: ''
      annt_file: datasets/robustvqa/robustvqa_test.json
      phase: 'v2'
      collator: ImageNetEvalCollator
      collate_mode: generate_imagenet
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path

      transform: *val_transform

    - name: pope-r

      data_root: datasets/coco/val2014
      annt_file: datasets/pope
      phase: 'random'
      collator: ImageNetEvalCollator
      collate_mode: generate_imagenet
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path

      transform: *val_transform

    - name: pope-a

      data_root: datasets/coco/val2014
      annt_file: datasets/pope
      phase: 'adversarial'
      collator: ImageNetEvalCollator
      collate_mode: generate_imagenet
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path

      transform: *val_transform

    - name: pope-p

      data_root: datasets/coco/val2014
      annt_file: datasets/pope
      phase: 'popular'
      collator: ImageNetEvalCollator
      collate_mode: generate_imagenet
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path

      transform: *val_transform





