# Training Arguments

fp16: True
max_steps: 20000
per_device_train_batch_size: &per_device_train_batch_size 4
per_device_eval_batch_size: 2
dataloader_num_workers: &num_workers 8
data_seed: &data_seed 0
seed: 32

## optimizer & scheduler

optim: adamw_torch
learning_rate: 1.0e-6
weight_decay: 0.05
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-8
lr_for_random_params_list: [1.0e-6, 1.0e-7, 1.0e-6, 1.0e-7, 1.0e-7, 1.0e-7]
wd_for_random_params_list: [0.0, 0.0, null, null, null, null]
random_params_list: [llama_cross_attn.gate, sampling_offsets, 
                    llama_cross_attn, visual_tokenizer.encoder.unet,
                    visual_tokenizer.sniffer.vision_model.visual,
                    visual_tokenizer.sniffer.vision_model.encoder]    

lr_scheduler_type: "cosine"
warmup_steps: 500

## evaluation & saving

evaluation_strategy: "steps"
eval_steps: 2000
save_strategy: "steps"
save_steps: 2000
save_total_limit: 5
fp16_full_eval: false

generate_mode: generate_both

## logging

report_to: ['tensorboard']
logging_steps: 10
disable_tqdm: False
log_level: info

## misc

tf32: True
ddp_find_unused_parameters: False

## deepspeed

deepspeed: './uni_interleaved/configs/deepspeed_zero1.json'


# MODEL
model:
  freeze_llm: True
  freeze_vfm: False
  freeze_dm: True
  llm_model_path: &tokenizer_path assets/lmsys/vicuna-7b-v1.5
  # llm_model_path: &tokenizer_path assets/lmsys/vicuna-13b-v1.3
  num_img_token: &img_len 77
  cross_attention_frequency: 4

  dataset_to_ignore_noimage_cond_loss: [laion_en, laion_coco]

  visual_tokenizer_config:
    sniffer_model_path: assets/laion/CLIP-convnext_base_w_320-laion_aesthetic-s13B-b82K
    # sniffer_model_path: assets/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup
    # sniffer_model_path: assets/openai/clip-vit-large-patch14
    # sniffer_model_path: assets/openai/clip-vit-base-patch16

    perceiver_config:
      num_queries: 77
      hidden_size: 768
      encoder_hidden_size: 1024
      cross_attention_frequency: 2
      num_hidden_layers: 12
      num_attention_heads: 12
      qk_normalization: True
  image_decoder_config:
    pretrained_model_name_or_path: assets/stabilityai/stable-diffusion-2-1-base
    sd_base_seed: 0
    sd_use_random_seed: False
    perceiver_config:
      num_queries: 77
      hidden_size: 1024
      encoder_hidden_size: 4096
      # encoder_hidden_size: 5120
      cross_attention_frequency: 1
      num_hidden_layers: 1
      num_attention_heads: 16
      hidden_dropout_prob: 0.
      attention_probs_dropout_prob: 0.
      
data:
  train:
    name: sft
    datasets:

    - name: coco_caption_karpathy
      data_root: datasets/coco
      annt_root: datasets/coco

      tokenizer_path: *tokenizer_path
      img_first_prob: 0.5
      collator: ImageTextPairTrainCollator
      num_img_token: *img_len

      transform: &train_transform
        aug_type: 'dual_numpy'
        resolution: &image_size 256
        resolution2: &image_size_dec 512

    - name: image2paragraph
      data_root: datasets/vg
      annt_root: datasets/image2parag

      img_first_prob: 0.5

      tokenizer_path: *tokenizer_path

      collator: ImageTextPairTrainCollator
      num_img_token: *img_len

      transform: *train_transform

    - name: flickr30kcaption
      data_root: datasets/flickr30k/flickr30k-images
      annt_root: datasets/flickr30k

      img_first_prob: 0.5

      tokenizer_path: *tokenizer_path

      collator: ImageTextPairTrainCollator
      num_img_token: *img_len

      transform: *train_transform

    - name: textcaps
      data_root: datasets/textvqa/train_images
      annt_root: datasets/textcaps

      img_first_prob: 0.5

      tokenizer_path: *tokenizer_path

      collator: ImageTextPairTrainCollator
      num_img_token: *img_len

      transform: *train_transform

    - name: lncoco
      data_root: datasets/coco
      annt_root: datasets/lncoco

      img_first_prob: 0.5

      tokenizer_path: *tokenizer_path

      collator: ImageTextPairTrainCollator
      num_img_token: *img_len

      transform: *train_transform
  val:
    - name: coco_caption

      data_root: datasets/coco
      annt_root: datasets/coco

      collator: ImageTextPairEvalCollator
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path
      collate_mode: generate_texts
      img_first_prob: 1.0

      transform: &val_transform
        aug_type: 'dual_numpy'
        resolution: *image_size
        resolution2: *image_size_dec
        center_crop: False
        random_flip: False

    # - name: flickr30kcaption
    #   data_root: datasets/flickr30k/flickr30k-images
    #   annt_file: datasets/flickr30k/flickr30k_test1k.json

    #   collator: ImageTextPairEvalCollator
    #   num_img_token: *img_len
    #   tokenizer_path: *tokenizer_path
    #   collate_mode: generate_texts
    #   img_first_prob: 1.0

    #   transform: *val_transform


    # - name: lncoco
    #   data_root: datasets/coco
    #   annt_root: datasets/lncoco

    #   collator: ImageTextPairEvalCollator
    #   num_img_token: *img_len
    #   tokenizer_path: *tokenizer_path
    #   collate_mode: generate_images
    #   img_first_prob: 0.0 
    #   total_length: 30_000

    #   transform: *val_transform

    - name: mscoco
      data_root: datasets/coco
      annt_root: datasets/coco

      collator: ImageTextPairEvalCollator
      num_img_token: *img_len
      tokenizer_path: *tokenizer_path
      collate_mode: generate_images
      img_first_prob: 0.0 
      total_length: 30_000

      transform: *val_transform